"""Create Prompt table

Revision ID: 870d1c1f275d
Revises: c73141c8e479
Create Date: 2026-08-01 14:47:37.352968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870d1c1f275d'
down_revision: Union[str, Sequence[str], None] = 'c73141c8e479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prompts',
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_name', sa.Text(), nullable=False),
    sa.Column('document_type_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['DocumentTypes.document_type_id'], ),
    sa.PrimaryKeyConstraint('prompt_id'),
    sa.UniqueConstraint('document_type_id'),
    sa.UniqueConstraint('prompt_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Prompts')
    # ### end Alembic commands ###
