"""Initial schema

Revision ID: c73141c8e479
Revises: 
Create Date: 2026-07-30 17:31:11.412340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73141c8e479'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentTypes',
    sa.Column('document_type_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_type_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('document_type_id'),
    sa.UniqueConstraint('document_type_name')
    )
    op.create_table('Documents',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_name', sa.Text(), nullable=False),
    sa.Column('total_page_number', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('process_stage', sa.Text(), nullable=False),
    sa.Column('document_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('document_type_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['DocumentTypes.document_type_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('Pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('page_png', sa.LargeBinary(), nullable=False),
    sa.Column('page_markdown', sa.Text(), nullable=False),
    sa.Column('process_stage', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['Documents.document_id'], ),
    sa.PrimaryKeyConstraint('document_id', 'page_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pages')
    op.drop_table('Documents')
    op.drop_table('DocumentTypes')
    # ### end Alembic commands ###
