"""Add extracted_data to Documents

Revision ID: e095fdfd4a48
Revises: 870d1c1f275d
Create Date: 2026-08-02 12:34:09.516377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e095fdfd4a48'
down_revision: Union[str, Sequence[str], None] = '870d1c1f275d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Documents', sa.Column('extracted_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Documents', 'extracted_data')
    # ### end Alembic commands ###
